package defs

import (
	"context"
)

// Database defines the common database interface
type Database interface {
	// Get returns a database connection
	Get() interface{}
	// Close closes the database connection
	Close() error
	// Ping checks if database is alive
	Ping(ctx context.Context) error
}

// SQLDatabase defines SQL database operations
type SQLDatabase interface {
	Database

	// Query executes a query that returns rows
	Query(ctx context.Context, query string, args ...interface{}) (Rows, error)
	// Exec executes a query without returning any rows
	Exec(ctx context.Context, query string, args ...interface{}) (Result, error)
	// Begin starts a transaction
	BeginTx(ctx context.Context, opts *TxOptions) (Transaction, error)
}

// Rows represents the result rows
type Rows interface {
	// Close closes the rows
	Close() error
	// Next prepares the next result row for reading
	Next() bool
	// Scan copies the columns in the current row into the values pointed at by dest
	Scan(dest ...interface{}) error
	// Err returns the error, if any, that was encountered during iteration
	Err() error
}

// Result is the result of an Exec query
type Result interface {
	// LastInsertId returns the integer generated by the database in response to a command
	LastInsertId() (int64, error)
	// RowsAffected returns the number of rows affected by the query
	RowsAffected() (int64, error)
}

// Transaction represents a database transaction
type Transaction interface {
	// Commit commits the transaction
	Commit() error
	// Rollback aborts the transaction
	Rollback() error

	// Query executes a query within the transaction
	Query(ctx context.Context, query string, args ...interface{}) (Rows, error)
	// Exec executes a query within the transaction
	Exec(ctx context.Context, query string, args ...interface{}) (Result, error)
}

// TxOptions holds the transaction options
type TxOptions struct {
	// Isolation is the transaction isolation level
	Isolation IsolationLevel
	// ReadOnly is the transaction read-only flag
	ReadOnly bool
}

// IsolationLevel is the transaction isolation level
type IsolationLevel int

const (
	LevelDefault IsolationLevel = iota
	LevelReadUncommitted
	LevelReadCommitted
	LevelWriteCommitted
	LevelRepeatableRead
	LevelSnapshot
	LevelSerializable
	LevelLinearizable
)
